variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- build

before_script:
- apt-get update -y
- apt-get install -y qt5-default qt5-qmake catch gdb librtaudio-dev

build_main:
  stage: build
  script:
    - qmake RtAudioStreamer.pro -r CONFIG+=debug
    - make
    