image: mxklb/docker-qt5-deb

stages:
- build
- deploy

before_script:
- apt-get update -y
- apt-get install -y catch gdb gcovr librtaudio-dev git
- git submodule update --init --recursive

debug_tests:
  stage: build
  script:
    - qmake RtAudioStreamer.pro -r CONFIG+=debug
    - make
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
    - gcovr -r . -e '.*extern.*' -e '.*moc_.*'

release_tests:
  stage: build
  script:
    - qmake RtAudioStreamer.pro -r CONFIG+=release
    - make

deploy_debian:
  stage: deploy
  only:
    - master
  script:
    - export USER="mxklb"
    - chmod +x pkgs/debian.sh
    - pkgs/debian.sh
    - mv pkgs/deb/rtaudiostreamer-*.deb .
  artifacts:
    paths:
      - rtaudiostreamer-*.deb
    name: "rtaudiostreamer.ubuntu14-04_amd64.deb"
