stages:
- build

before_script:
- apt-get update -y
- apt-get install -y qt5-default qt5-qmake catch gdb librtaudio-dev
- git submodule update --init --recursive

build_main:
  stage: build
  script:
    - qmake RtAudioStreamer.pro -r CONFIG+=debug
    - make
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
    